import * as global from "../global.js";
import { Gltf2Node } from "../render/nodes/gltf2.js";

export let buddha;

export default () => {
   global.scene().addNode(new Gltf2Node({
      url: ""
   })).name = "backGround";

   return {
      enableSceneReloading: true,
      scenes: [ 
//          { name: "example1"           , path: "./example1.js"           , public: false },
//          { name: "example2"           , path: "./example2.js"           , public: false },
//          { name: "example3"           , path: "./example3.js"           , public: false },
//          { name: "example4"           , path: "./example4.js"           , public: false },
//          { name: "example5"           , path: "./example5.js"           , public: false },
//          { name: "example6"           , path: "./example6.js"           , public: false },
//          { name: "example7"           , path: "./example7.js"           , public: false },
//          { name: "example8"           , path: "./example8.js"           , public: false },

            { name: "wordcloud"          , path: "./wordcloud.js"          , public: true  },
            { name: "wordcloud2"         , path: "./wordcloud2.js"         , public: true  },
            { name: "wordcloud3"         , path: "./wordcloud3.js"         , public: true  },
            { name: "wordcloud4"         , path: "./wordcloud4.js"         , public: true  },
            { name: "wordcloud5"         , path: "./wordcloud5.js"         , public: true  },
            { name: "wordcloud6"         , path: "./wordcloud6.js"         , public: true  },
            { name: "wordcloud7"         , path: "./wordcloud7.js"         , public: true  },

            { name: "fractal"            , path: "./fractal.js"            , public: true  },
//          { name: "nestedA"            , path: "./nestedA.js"            , public: true  },
//          { name: "nestedB"            , path: "./nestedB.js"            , public: true  },
            { name: "textured"           , path: "./textured.js"           , public: true  },

            { name: "particleNoise"      , path: "./particleNoise.js"      , public: true  },

            { name: "testAvatar"         , path: "./testAvatar.js"         , public: true  },
            { name: "testIKBody"         , path: "./testIKBody.js"         , public: true  },

//          { name: "pinscreen"          , path: "./pinscreen.js"          , public: true  },
//          { name: "share_ball"         , path: "./share_ball.js"         , public: false },
//          { name: "drag_objects"       , path: "./drag_objects.js"       , public: false },
//          { name: "drag_objects2"      , path: "./drag_objects2.js"      , public: false },
//          { name: "build_noise"        , path: "./build_noise.js"        , public: false },
//          { name: "ellipsoid"          , path: "./ellipsoid.js"          , public: false },
//          { name: "quaternion"         , path: "./quaternion.js"         , public: false },
//          { name: "ik_robot"           , path: "./ik_robot.js"           , public: false },
//          { name: "ik_code"            , path: "./ik_code.js"            , public: false },
//          { name: "wheelie"            , path: "./wheelie.js"            , public: false},
//          { name: "DemoAudio"          , path: "./demoAudio.js"          , public: false},
//          { name: "DemoBlending"       , path: "./demoBlending.js"       , public: false},
//          { name: "DemoControllerBeam" , path: "./demoControllerBeam.js" , public: false},
//          { name: "DemoControllers"    , path: "./demoControllers.js"    , public: false},
//          { name: "DemoCroquet"        , path: "./demoCroquet.js"        , public: false},
//          { name: "demoHands"          , path: "./demoHands.js"          , public: false},
          { name: "DemoHUD"            , path: "./demoHUD.js"            , public: false},
//          { name: "DemoIntersect"      , path: "./demoIntersect.js"      , public: false},
//          { name: "DemoOpacity"        , path: "./demoOpacity.js"        , public: false},
//          { name: "DemoParticles"      , path: "./demoParticles.js"      , public: false},
//          { name: "DemoParticles2"     , path: "./demoParticles2.js"     , public: false},
//          { name: "DemoRayTrace"       , path: "./demoRayTrace.js"       , public: false},
//          { name: "DemoRobot"          , path: "./demoRobot.js"          , public: false},
//          { name: "DemoShader"         , path: "./demoShader.js"         , public: false},
//          { name: "DemoShapes"         , path: "./demoShapes.js"         , public: false},
//          { name: "DemoSimplest"       , path: "./demoSimplest.js"       , public: false},
//          { name: "demoShared"         , path: "./demoShared.js"         , public: false},
//          { name: "DemoSprite"         , path: "./demoSprite.js"         , public: false},
//          { name: "DemoTerrain"        , path: "./demoTerrain.js"        , public: false},
//          { name: "DemoTrianglesMesh"  , path: "./demoTrianglesMesh.js"  , public: false},
//          { name: "DemoTwoCubes"       , path: "./demoTwoCubes.js"       , public: false},
//          { name: "DemoWire"           , path: "./demoWire.js"           , public: false},
//          { name: "seatChart"          , path: "./demoSeatChart.js"      , public: false},
//          { name: "molecules"          , path: "./demoMolecules.js"      , public: false},
//          { name: "canvas"             , path: "./demoCanvas.js"         , public: false},
            { name: "canvas2"            , path: "./demoCanvas2.js"        , public: true },
//          { name: "creature"           , path: "./demoCreature.js"       , public: false},
//          { name: "bounds"             , path: "./demoBounds.js"         , public: false},
//          { name: "chart"              , path: "./demoChart.js"          , public: false },
//          { name: "chess"              , path: "./demoChess.js"          , public: false },
//          { name: "chess2"             , path: "./demoChess2.js"         , public: false },
//          { name: "classroom"          , path: "./demoClassroom.js"      , public: false},
//          { name: "code"               , path: "./demoCode.js"           , public: true },
//          { name: "code_shader"        , path: "./demoCode2.js"          , public: false}, 
//          { name: "construct"          , path: "./demoBalls.js"          , public: true },
            { name: "crayon"             , path: "./demoDraw.js"           , public: true },
//          { name: "agent"              , path: "./demoAgent.js"          , public: false},
            { name: "diagram"            , path: "./demoDiagram.js"        , public: false},
//          { name: "dodeca"             , path: "./demoDodeca.js"         , public: false},
//          { name: "dots"               , path: "./demoDots.js"           , public: false},
//          { name: "exhibit"            , path: "./demoExhibit.js"        , public: false},
//          { name: "gallery"            , path: "./demoGallery.js"        , public: false },
//          { name: "gesture"            , path: "./demoGesture.js"        , public: false},
//          { name: "hypercube"          , path: "./demo4D.js"             , public: false },
//          { name: "layers"             , path: "./demoLayers.js"         , public: false},
//          { name: "mesh detection"     , path: "./demoMeshDetection.js"  , public: false},
//          { name: "mist"               , path: "./demoMist.js"           , public: false},
//          { name: "moon"               , path: "./demoMoon.js"           , public: false },
//          { name: "moon2"              , path: "./demoMoon2.js"          , public: false },
//          { name: "morph"              , path: "./demoRhombi.js"         , public: false },
//          { name: "noise"              , path: "./demoNoise.js"          , public: false},
//          { name: "pedestal"           , path: "./demoPedestal.js"       , public: false},
//          { name: "piano2"             , path: "./demoPiano2.js"         , public: false},
//          { name: "puzzle"             , path: "./demoPuzzle.js"         , public: false },
//          { name: "shader"             , path: "./demoShaderNew.js"      , public: false},
//          { name: "skylight"           , path: "./demoSkylight.js"       , public: false },
//          { name: "smoke"              , path: "./demoSmoke.js"          , public: false },
//          { name: "snowOriginal"       , path: "./demoSnow.js"           , public: false},
//          { name: "snow"               , path: "./demoSnowDots.js"       , public: false },
//          { name: "snow2"              , path: "./demoSnow2.js"          , public: false},
          { name: "statue"             , path: "./demoGLTF.js"           , public: true },
            { name: "attic"              , path: "./attic.js"              , public: false },
//          { name: "sync"               , path: "./demoSync.js"           , public: false},
//          { name: "table"              , path: "./demoTable.js"          , public: false},
//          { name: "telekinesis"        , path: "./demoTelekinesis.js"    , public: false },
//          { name: "text"               , path: "./demoText.js"           , public: false},
//          { name: "toios"              , path: "./demoToios.js"          , public: false},
//          { name: "uiBox"              , path: "./demoUIBox.js"          , public: false},
//          { name: "window"             , path: "./demoWindow.js"         , public: false },
//          { name: "tabletop"           , path: "./tabletop.js"           , public: true },
//          { name: "4D2"                , path: "./demo4D2.js"            , public: false},
//          { name: "syncsender"         , path: "./demoSyncSender.js"     , public: false},
//          { name: "syncreceriver"      , path: "./demoSyncReceiver.js"   , public: false},
//          { name: "saveroom"           , path: "./demoSaveRoom.js"       , public: false},
//          { name: "roomsender"         , path: "./demoRoomSender.js"     , public: false},
//          { name: "roomreceriver"      , path: "./demoRoomReceiver.js"   , public: false},
//          { name: "roomdebug"          , path: "./demoRoomDebug.js"      , public: false},
//          { name: "physics"            , path: "./demoPhysics.js"        , public: false},
//          { name: "image_generation"   , path: "./demoImageGeneration.js", public: false},
//          { name: "offset"             , path: "./demoOffset.js"         , public: false},
//          { name: "spinning sound"     , path: "./demoSpinningSound.js"  , public: false },
//          { name: "forest"             , path: "./demoForest.js"         , public: false },
      //    // { name: "spatial audio test" , path: "./demoSpatialAudioWrapper.js"         , public: true },
      //    { name: "spatial audio wrapper" , path: "./demoSoundWrapper.js" , public: false },
      //    { name: "opti-track"         , path: "./demoTrack.js"          , public: false },
      //    { name: "opti-track-offset" , path: "./demoTrackOffset.js"    , public: false },
      ]
   };
}

